# Generated by Django 3.1.3 on 2020-11-25 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=7)),
                ('type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('latitude_deg', models.CharField(max_length=30)),
                ('longitude_deg', models.CharField(max_length=30)),
                ('elevation_ft', models.DecimalField(decimal_places=5, max_digits=10)),
                ('continent', models.CharField(max_length=30)),
                ('iso_country', models.CharField(max_length=2)),
                ('iso_region', models.CharField(max_length=10)),
                ('municipality', models.CharField(max_length=100)),
                ('scheduled_service', models.CharField(max_length=30)),
                ('gps_code', models.CharField(max_length=10)),
                ('iata_code', models.CharField(max_length=10)),
                ('local_code', models.CharField(max_length=10)),
                ('home_link', models.URLField()),
                ('wikipedia_link', models.URLField()),
                ('keywords', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created', 'created_by', 'name', 'iso_country'],
            },
        ),
    ]
