# Generated by Django 3.1.3 on 2020-11-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='home_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='keywords',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
